# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# title: 10x Mind Pump Program
# description: Personalised program to hit my target gains in 2-3 months! ðŸ™ƒ

## Modernist
remote_theme: pages-themes/modernist@v0.2.0

title: Wimpy to Healthy
description: 10x Mind Pump Program. Grind, Rinse then Repeat!
show_downloads: false